### PR TITLE
feat: init project

### PR DESCRIPTION
**Pull request by ONE7live**

### CODE REVIEW

**Comment by duanmengkk** [comment]
The .idea directory does not need to be committed to the repository.

**Comment by duanmengkk** [comment]
PLZ  add repository OWNERs

**Comment by duanmengkk** [comment]
Please add a detailed README document and explain the relationship of this repository with Kosmos.

**Comment by ONE7live** [comment]
> The .idea directory does not need to be committed to the repository.

done, and add '.gitignore' file

**Comment by ONE7live** [comment]
> PLZ add repository OWNERs

done, add 'OWNERS' file and owners: @ONE7live , @GreatLazyMan , @OrangeBao

**Comment by ONE7live** [comment]
> Please add a detailed README document and explain the relationship of this repository with Kosmos.

Can I submit it in another PR? This will not affect the development of other functions

**Pull request merged**
